language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
sudo: required

before_deploy:
  - npm i
  - npm run build:package
  - cd dist

deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  api_key:
    secure: KEY-NEEDED
  on:
    tags: true
    repo: @hmcts/angular-form-builder
